# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-24 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_trayecto_partida'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trayecto',
            new_name='Proyecto',
        ),
    ]
