# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20170524_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='partida',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
