# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20170619_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='latitudeDE',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='latitudeOR',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='longitudeDE',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='longitudeOR',
        ),
    ]
