# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-04 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20170704_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
